### PR TITLE
Update zh_cn

### PR DESCRIPTION
**Pull request by ChuijkYahus**
Sorry for the late hotfixes.
This PR only changes 2 places, one for preventing too much text being rendered into a smaller size, one for fixing a typo.

could be left until next large update and merge together with new translations tho.

### CODE REVIEW

**Comment by SamsTheNerd** [comment]
no problem, I've got some of my own code related hotfixes I need to push out in the next few days anyways lol. 

Few things I want to tweak in the english book related to things I've seen people be confused about, idk how closely you translate or if you'll want to change anything to match it, but I'll make sure to put those in their own commit so they're easy to catch.

**Comment by SamsTheNerd** [comment]
oof, forgot about this before publishing, I'll get it next update.

**Comment by SamsTheNerd** [comment]
Should have all the lang keys in for next update, let me know when you're done and ready for it all to be merged in and released !

**Comment by SamsTheNerd** [comment]
oops, a few more i forgot

**Comment by SamsTheNerd** [comment]
oops, forgot some more sorry, pushed now.

**Comment by ChuijkYahus** [comment]
Ready to be merged now!

The key value for dreidel in en_us seems to be the same as Pen Fidget, have changed that to its proper name in zh_cn.
"Mept" is translated into "使偶" as in "Familiar Idol(some stature)". Familiar on itself is usually trsled as "使魔", kind of named after that. Hope that fits well.

**Comment by SamsTheNerd** [comment]
Wonderful ! 

The mept translation sound perfect.

Thanks so much for your work and contributions <3

**Pull request merged**
